version: '3.8'

services:

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.0.2
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
  kibana:
    image: docker.elastic.co/kibana/kibana:9.0.2
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://elastic:9200
#  zookeeper:
#    image: confluentinc/cp-zookeeper:7.3.0
#    environment:
#      ZOOKEEPER_CLIENT_PORT: 2181
#    ports:
#      - "2181:2181"
#
#  kafka:
#    image: confluentinc/cp-kafka:7.3.0
#    depends_on:
#      - zookeeper
#    ports:
#      - "9092:9092"
#    environment:
#      KAFKA_BROKER_ID: 1
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
#      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#
#  mysql:
#    image: mysql:8.0
#    container_name: mysql
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#      MYSQL_DATABASE: tiki-product
#      MYSQL_USER: root
#      MYSQL_PASSWORD: "password"
#    ports:
#      - "3305:3306"
#    command:
#      --server-id=223344 --log-bin=mysql-bin --binlog-format=ROW --binlog-row-image=FULL
#
#  connect:
#    image: debezium/connect:2.4
#    depends_on:
#      - kafka
#      - mysql
#    ports:
#      - "8883:8083"
#    environment:
#      BOOTSTRAP_SERVERS: kafka:9092
#      GROUP_ID: 1
#      CONFIG_STORAGE_TOPIC: my_connect_configs
#      OFFSET_STORAGE_TOPIC: my_connect_offsets
#      STATUS_STORAGE_TOPIC: my_connect_statuses
#      KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
#      VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
#      CONNECT_REST_ADVERTISED_HOST_NAME: connect
#      CONNECT_GROUP_ID: kafka-connect-group
#      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
#      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
#      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
#      CONNECT_PLUGIN_PATH: /kafka/connect,/debezium/connectors
#    volumes:
#      - ./debezium-plugins:/kafka/connect
#
#  ## 🔍 Kafka UI
#  kafka-ui:
#    image: provectuslabs/kafka-ui:latest
#    ports:
#      - "8880:8080"
#    depends_on:
#      - kafka
#      - zookeeper
#    environment:
#      KAFKA_CLUSTERS_0_NAME: local
#      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
#      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
