version: '3.8'

services:

#  elastic:
#    image: docker.elastic.co/elasticsearch/elasticsearch:9.0.2
#    ports:
#      - 9200:9200
#    environment:
#      - discovery.type=single-node
#      - xpack.security.enabled=false
#      - xpack.security.http.ssl.enabled=false
#  kibana:
#    image: docker.elastic.co/kibana/kibana:9.0.2
#    ports:
#      - 5601:5601
#    environment:
#      - ELASTICSEARCH_HOSTS=http://elastic:9200
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: tiki-product
      MYSQL_USER: thuan
      MYSQL_PASSWORD: "password"
    ports:
      - "3305:3306"
    command:
      --server-id=223344 --log-bin=mysql-bin --binlog-format=ROW --binlog-row-image=FULL
  zookeeper:
    image: zookeeper
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
  kafka:
    image: docker.io/bitnami/kafka
    ports:
      - 9092:9092
      - 9093:9093
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka:9092,EXTERNAL://127.0.0.1:9093
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_LISTENERS=INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:9093
    depends_on:
      - zookeeper
  connect:
    image: debezium/connect:2.7.3.Final
    ports:
      - 8083:8083
      - 8778:8778
    links:
      - kafka
      - mysql
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - GROUP_ID=debezium-events
      - CONFIG_STORAGE_TOPIC=debezium_configs
      - OFFSET_STORAGE_TOPIC=debezium_offsets
      - STATUS_STORAGE_TOPIC=debezium_statuses
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
      - KAFKA_CLUSTERS_0_SCHEMA_REGISTRY=http://localhost:8081
      - SPRING_PROFILES_ACTIVE=prod
    ports:
      - "9000:8080"
    depends_on:
      - kafka
#  zookeeper:
#    image: quay.io/debezium/zookeeper:3.2
#    container_name: demo_zookeeper
#    ports:
#      - 2181:2181
#      - 2888:2888
#      - 3888:3888
#  kafka:
#    image: quay.io/debezium/kafka:3.2
#    container_name: demo_kafka
#    ports:
#      - 9092:9092
#    links:
#      - zookeeper
#    environment:
#      - ZOOKEEPER_CONNECT=zookeeper:2181
#  kafka-ui:
#    image: provectuslabs/kafka-ui:latest
#    container_name: demo_kafka-ui
#    environment:
#      KAFKA_CLUSTERS_0_NAME: local
#      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: demo_kafka:9092
#    ports:
#      - "9089:8080"
#    links:
#      - kafka
#
#  connect:
#    image: quay.io/debezium/connect:3.2
#    container_name: demo_connect
#    ports:
#      - 8883:8083
#    links:
#      - kafka
#      - mysql
#    environment:
#      - BOOTSTRAP_SERVERS=kafka:9092
#      - GROUP_ID=1
#      - CONFIG_STORAGE_TOPIC=my_connect_configs
#      - OFFSET_STORAGE_TOPIC=my_connect_offsets
#      - STATUS_STORAGE_TOPIC=my_connect_statuses