server:
  port: 8888
app:
  api-prefix: /api/v1

spring:
  application:
    name: api-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/tiki
  cloud:
    gateway:
      routes:
        - id: profile_service
          uri: http://localhost:8081
          predicates:
            - Path=${app.api-prefix}/profiles/**
          filters:
            - StripPrefix=2
        - id: product_service
          uri: http://localhost:8082
          predicates:
            - Path=${app.api-prefix}/products/**
          filters:
            - StripPrefix=2
        - id: file_service
          uri: http://localhost:8083
          predicates:
            - Path=${app.api-prefix}/files/**
          filters:
            - StripPrefix=2
        - id: search_service
          uri: http://localhost:8087
          predicates:
            - Path=${app.api-prefix}/files/**
          filters:
            - StripPrefix=2

idp:
  url: http://localhost:8180
  client-id: tiki_app
  client-secret: UpN6e6X1lzKYrIIYCysdeWGgYVYMun0A