server:
    port: 8086
    servlet:
        context-path: /payments
spring:
    application:
        name: payment-service
    datasource:
        url: jdbc:mysql://localhost:3306/tiki-payment
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: 'password'
        jpa:
            hibernate:
                ddl-auto: update
            show-sql: true
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: http://localhost:8180/realms/tiki
idp:
    url: http://localhost:8180
    client-id: tiki_app
    client-secret: UpN6e6X1lzKYrIIYCysdeWGgYVYMun0A
payment:
    vnPay:
        url: "https://sandbox.vnpayment.vn/paymentv2/vpcpay.html"
        tmnCode: "EDT2E52Y"
        secretKey: "VGC6H4EJ834TXE5USIHM20W3FH4469VW"
        returnUrl: "http://localhost:8085/payments/vn-pay-callback"
        version: "2.1.0"
        command: "pay"
        orderType: "other"