server:
  port: 8085
  servlet:
    context-path: /carts
spring:
  application:
    name: cart-service
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/cart-service?authSource=admin
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/tiki
idp:
  url: http://localhost:8180
  client-id: tiki_app
  client-secret: Y1GleohK65RsIur2eYWCZ9dGNJ8Ta5Rx